### ISSUE TITLE
enhancement: Introduce a way to count scores

### ISSUE THREAD

**Issue by eljhkrr** [pixelastic/pokemonorbigdata#10]

**Comment by pixelastic** [comment]
What do you mean by counting scores? Something like a leaderboard of all the best players, or a way to track your current score as you go along the game?

**Comment by eljhkrr** [comment]
I meant a way to track your own score each time the 'game' is played.

**Comment by pixelastic** [comment]
Oh I see. I don't feel like this is the kind of game you want to play several times, so I'm unsure this is really useful. 

I don't think I'll code that myself, but I'm open to pull requests.

**Comment by eljhkrr** [comment]
Good point. I'll just close this
