### ISSUE TITLE
Inverse answers do not add up to 100%

### ISSUE THREAD

**Issue by MikeThomas1** [pixelastic/pokemonorbigdata#13]
If I answer all Pokemon I get a score of 46%. 
If I answer all Big Data I get a score of 53%. 
These two scores add up to 99%. 

Expected result: Scores add up to 100%.

**Comment by pixelastic** [comment]
The percent displayed is not the exact value, I'm rounding it for display, to make it look nicer. So yes, it is expected that the sum is not perfect.

I don't think this is something that can be fixed (unless having exactly 100 questions).

**Comment by tofu-rocketry** [comment]
How about using `Math.round` rather than `Math.floor`?

**Comment by pixelastic** [comment]
Oh, I actually thought I was using `Math.round` already. Thanks, I've updated the code :)
