### ISSUE TITLE
[Improvement] "Who's that Pokemon?" Template

### ISSUE THREAD

**Issue by Laptopmini** [pixelastic/pokemonorbigdata#22]
HUGE opportunity missed to use the following template:
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtaCV1Fg0lBDHqUACEKd2qUgYq0H-pKGA0bn-ptdXhGgsKIleR

😛 

Awesome website lol 👏

**Comment by pixelastic** [comment]
I'm not aware of what this image is. Could you elaborate a bit? :)

**Comment by LavenderTheGreat** [comment]
It was a minigame at the end of Pokemon anime episodes. That version is from the original anime, a silhouette of the Pokémon would be in the spark.

**Comment by pixelastic** [comment]
I agree it would be great to have this image as a background when displaying the result as a pokemon, but I won't have time to add it myself. I'm open to pull request if you want to give it a try.
