### ISSUE TITLE
Add Lodash

### ISSUE THREAD

**Issue by jxu** [pixelastic/pokemonorbigdata#25]
While a JS framework and not big data, I legitimately thought Lodash was a Pokemon (probably because Lotad and Rapidash are both actual Pokemon) so maybe it can fit in.

**Comment by pixelastic** [comment]
That's a pretty good joke, I admit. I don't think I'll accept it in this website as I'd like to stay focused on big data.

Maybe you could create a fork (or build your own, the stack of this website is pretty old) for "Pokemon or JavaScript"? I'm sure it will be very popular :)
