### ISSUE TITLE
Play in a team setting

### ISSUE THREAD

**Issue by BenjaminShinar** [pixelastic/pokemonorbigdata#26]
I was wondering if there was a way to use the game in a team settings.
Like bringing this to Kahoot or Quizizz or some other platform.

not sure what steps would be involved in getting this online,
But I think it can be a somewhat popular thing.

**Comment by pixelastic** [comment]
Hello,

That could be a fun idea for sure. All the code is open source, so if you have experience with Kahoot or Quizizz (which I don't), you should be able to build something. Specifically, all the questions/answers are available here: https://github.com/pixelastic/pokemonorbigdata/blob/master/app/questions.json

I don't personally have time to build that, so I'll close the issue, but if you ever build something in that regard, I'll gladly accept a PR.

Cheers,
