### ISSUE TITLE
unknown option: --extension  as running ./script/build

### ISSUE THREAD

**Issue by APIPLM** [pixelastic/pokemonorbigdata#32]
After installing the `jsx` package  by running the command `yarn add jsx`. Run `yarn install` in the project. Then run `script/build`. But the following error message come out. 
` unknown option: --extension `

Can you have a time to take a look. Thanks in advanced.

**Comment by APIPLM** [comment]
```
jsx --version 
0.9.89 (2014-05-20 06:01:03 +0900; 8e8c6105f36f3dfe440ea026a3c93a3444977102)
```

**Comment by pixelastic** [comment]
Hello,

You don't need to install `jsx` manually, a version of `jsx` is already installed with `react-tools`. Note that this is a *very* old project, using v0.13.

**Comment by APIPLM** [comment]
Thanks. it is quite old, Even the `react-tools` package got deprecated as well. Now it has `@babel/plugin-transform-react-jsx` package transform the `jsx ` file to the `js `file in the building process.
