### ISSUE TITLE
Congratulations Message Grammar

### ISSUE THREAD

**Issue by jaredpetersen** [pixelastic/pokemonorbigdata#6]
The congratulations message at the end of the test is written as "Congratulation, you did 100%". "Congratulation" should be plural ("Congratulations") and the rest of the message "you did 100%" should probably be something like "you scored 100%" instead.

**Comment by pixelastic** [comment]
Someone already submitted a PR for that: #1 

The new text will be "Congratulations, you got {percent}% correct!". I still have to push the new version online. Will do soon.

**Comment by jaredpetersen** [comment]
Sorry, I only looked at the open PRs. Thanks!
