### ISSUE TITLE
General Grammar Problems

### ISSUE THREAD

**Issue by jaredpetersen** [pixelastic/pokemonorbigdata#7]
There are a ton of grammatical errors in the short blurbs that are located underneath the quiz answers.

**Comment by pixelastic** [comment]
Do you mind pointing them out with possible correction so I can update the website?

**Comment by paul42** [comment]
I've made a PR #8 to address this, please review

**Comment by pixelastic** [comment]
Thanks @jaredpetersen and @paul42. I've accepted the PR, I'll push to the website soon.
