### ISSUE TITLE
Add links to Big Data technologies

### ISSUE THREAD

**Issue by VikramTiwari** [pixelastic/pokemonorbigdata#9]

**Comment by pixelastic** [comment]
That's actually a pretty good idea! I'll add that, thanks.

**Comment by pixelastic** [comment]
I've just pushed it with 47b6cf98c7c09cae719ee64c07fb129621bea48a.

A lot of the big data technologies have been acquired, are dead, or have no website, do some links points to the Wikipedia instead...

**Comment by VikramTiwari** [comment]
:+1: Nice.
